apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-depl
  namespace: "{{.Values.namespace}}"
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: "{{.Values.appName}}"
      replica: green
  template:
    metadata:
      labels:
        app: "{{.Values.appName}}"
        replica: green
    spec:
      containers:
      - name: "{{.Values.appName}}"
        image: "{{.Values.greenImage.repository}}:{{.Values.greenImage.tag}}"
        resources:
          resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        startupProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 5
      imagePullSecrets:
      - name: dockerhub-secret
