apiVersion: v1
kind: Service
metadata:
  name: bluegreen-svc
  namespace: "{{.Values.blueImage.namespace}}"
  labels:
    app: "{{.Values.appName}}"
spec:
  type: NodePort
  selector:
    app: "{{.Values.appName}}"
    replica: {{.Values.currentDeployment}}
  ports:
    - protocol: TCP
      port: 80          # Port that the service exposes
      targetPort: 80    # Port on the container to forward to
      nodePort: 30003