apiVersion: v1
kind: Service
metadata:
  name: canary-svc
  namespace: test
spec:
  type: NodePort
  selector:
    app: canaryApp
  ports:
    - protocol: TCP
      port: 80          # Port that the service exposes
      targetPort: 80    # Port on the container to forward to
      nodePort: 30004