apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-depl
  namespace: test
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: bluegreen-app
      replica: green
  template:
    metadata:
      labels:
        app: bluegreen-app
        replica: green
    spec:
      containers:
      - name: bluegreen-app
        image: DOCKERHUB_USER/REPOSITORY:TAG
        resources:
          resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        startupProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 5
      imagePullSecrets:
      - name: dockerhub-secret
